import { Designer, Project, Exhibition } from '../types';

export const DESIGNERS: Designer[] = [
  {
    id: 'choi-eunsol',
    name: 'Choi Eunsol',
    nameKo: '최은솔',
    mainRole: 'Fashion Designer',
    role: 'Fashion Designer',
    bio: '전통과 현대를 융합한 독특한 미학을 추구하는 패션 디자이너입니다.',
    profileImage: 'https://ik.imagekit.io/t914/redux/designers/choieunsol/choieunsol-Profile.jpeg',
    coverImage: 'https://ik.imagekit.io/t914/redux/designers/choieunsol/cinemode/IMG_8617.jpeg',
    instagramHandle: '@choieunsol.of',
    portfolioImages: [
      'https://ik.imagekit.io/t914/redux/designers/choieunsol/cinemode/IMG_8617.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/choieunsol/cinemode/IMG_8618.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/choieunsol/cinemode/IMG_8619.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/choieunsol/cinemode/IMG_8620.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/choieunsol/cinemode/IMG_8621.jpeg',
    ],
    featured: true,
    order: 1,
  },
  {
    id: 'park-parang',
    name: 'Park Parang',
    nameKo: '박파랑',
    mainRole: 'Fashion Designer',
    role: 'Visual Artist',
    bio: '시각 예술과 패션의 경계를 넘나드는 멀티미디어 아티스트입니다.',
    profileImage: 'https://ik.imagekit.io/t914/redux/profile/Park_Parang.jpg',
    coverImage: 'https://ik.imagekit.io/t914/redux/profile/Park_Parang.jpg',
    instagramHandle: '@rannx8m',
    portfolioImages: [
      'https://ik.imagekit.io/t914/redux/profile/Park_Parang.jpg',
    ],
    featured: true,
    order: 2,
  },
  {
    id: 'lee-taehyeon',
    name: 'Lee Taehyeon',
    nameKo: '이태현',
    mainRole: 'Fashion Designer',
    role: 'Fashion Designer',
    bio: '미니멀리즘과 구조적 실루엣을 탐구하는 패션 디자이너입니다.',
    profileImage: 'https://ik.imagekit.io/t914/redux/profile/Lee_Taehyeon.jpg',
    coverImage: 'https://ik.imagekit.io/t914/redux/designers/leetaehyeon/cinemode/KakaoTalk_20250628_134001383_01.jpg',
    instagramHandle: '@tododope',
    portfolioImages: [
      'https://ik.imagekit.io/t914/redux/designers/leetaehyeon/cinemode/KakaoTalk_20250628_134001383_01.jpg',
      'https://ik.imagekit.io/t914/redux/designers/leetaehyeon/cinemode/KakaoTalk_20250628_134001383_02.jpg',
      'https://ik.imagekit.io/t914/redux/designers/leetaehyeon/portfolio/15.png',
      'https://ik.imagekit.io/t914/redux/designers/leetaehyeon/portfolio/21.png',
    ],
    featured: false,
    order: 3,
  },
  {
    id: 'kim-bomin',
    name: 'Kim Bomin',
    nameKo: '김보민',
    mainRole: 'Fashion Designer',
    role: 'Creative Designer',
    bio: '색채와 텍스처를 통해 감정을 표현하는 크리에이티브 디자이너입니다.',
    profileImage: 'https://ik.imagekit.io/t914/redux/profile/Kim_Bomin.webp',
    coverImage: 'https://ik.imagekit.io/t914/redux/designers/kimbomin/cinemode/NOR_7419-11.jpg',
    instagramHandle: '@minectivbe',
    portfolioImages: [
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/cinemode/KakaoTalk_20250626_002430368_14.jpg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/cinemode/KakaoTalk_20250626_002430368_15.jpg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/cinemode/NOR_7419-11.jpg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/cinemode/김보민_사진.jpg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/portfolio/KakaoTalk_Photo_2025-06-28-13-18-36_001.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/portfolio/KakaoTalk_Photo_2025-06-28-13-18-36_002.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/portfolio/KakaoTalk_Photo_2025-06-28-13-18-36_003.jpeg',
      'https://ik.imagekit.io/t914/redux/designers/kimbomin/portfolio/KakaoTalk_Photo_2025-06-28-13-18-36_004.jpeg',
    ],
    featured: false,
    order: 4,
  },
  {
    id: 'kim-gyeongsu',
    name: 'Kim Gyeongsu',
    nameKo: '김경수',
    mainRole: 'Fashion Designer',
    role: 'Fashion Designer',
    bio: '기능성과 예술성을 결합한 혁신적인 패션을 선보이는 디자이너입니다.',
    profileImage: 'https://ik.imagekit.io/t914/redux/profile/Kim_Gyeongsu.webp',
    coverImage: 'https://ik.imagekit.io/t914/redux/designers/kimgyeongsu/Showcase/IMG_2544.jpg',
    instagramHandle: '@gang._.soo__',
    portfolioImages: [
      'https://ik.imagekit.io/t914/redux/designers/kimgyeongsu/Showcase/IMG_2544.jpg',
      'https://ik.imagekit.io/t914/redux/designers/kimgyeongsu/Showcase/IMG_5568.JPG',
      'https://ik.imagekit.io/t914/redux/designers/kimgyeongsu/Showcase/IMG_5939.jpg',
    ],
    featured: false,
    order: 5,
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'redux-2024-collection',
    title: 'REDUX 2024 Collection',
    titleKo: 'REDUX 2024 컬렉션',
    description: 'A revolutionary collection that challenges the boundaries between fashion and art.',
    descriptionKo: '패션과 예술의 경계에 도전하는 혁신적인 컬렉션입니다.',
    category: 'collective',
    designers: ['choi-eunsol', 'park-parang'],
    images: [
      'https://ik.imagekit.io/t914/redux/collective/main-cover.jpg',
      'https://ik.imagekit.io/t914/redux/collective/image-1.jpg',
      'https://ik.imagekit.io/t914/redux/collective/image-2.jpg',
    ],
    videoUrl: 'https://ik.imagekit.io/t914/redux/videos/redux-2024-collection.mp4',
    date: '2024-03-15',
    featured: true,
    order: 1,
  },
  {
    id: 'visual-art-exhibition',
    title: 'Visual Art Exhibition',
    titleKo: '비주얼 아트 전시',
    description: 'An immersive visual art experience exploring the intersection of fashion and contemporary art.',
    descriptionKo: '패션과 현대 예술의 교차점을 탐구하는 몰입형 비주얼 아트 경험입니다.',
    category: 'visual-art',
    designers: ['park-parang', 'kim-bomin'],
    images: [
      'https://ik.imagekit.io/t914/redux/visual-art/Collective_Vision.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Digital_Dreams.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Form_&_Void.png',
    ],
    date: '2024-02-10',
    featured: true,
    order: 2,
  },
  {
    id: 'memory-installation',
    title: 'Memory Installation',
    titleKo: '기억의 설치미술',
    description: 'An interactive installation exploring the relationship between memory, identity, and fashion.',
    descriptionKo: '기억, 정체성, 그리고 패션 사이의 관계를 탐구하는 인터랙티브 설치 작품입니다.',
    category: 'installation',
    designers: ['lee-taehyeon', 'kim-gyeongsu'],
    images: [
      'https://ik.imagekit.io/t914/redux/memory/IMG_7237.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3452.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_5380.JPG',
    ],
    date: '2024-01-20',
    featured: false,
    order: 3,
  },
];

export const CATEGORIES = {
  collective: {
    id: 'collective',
    title: 'Collective',
    titleKo: '컬렉티브',
    description: '협업과 공동 창작을 통한 새로운 가능성을 발견합니다',
    coverImage: 'https://ik.imagekit.io/t914/redux/collective/main-cover.jpg',
    images: [
      'https://ik.imagekit.io/t914/redux/collective/image-1.jpg',
      'https://ik.imagekit.io/t914/redux/collective/image-2.jpg',
    ],
  },
  'visual-art': {
    id: 'visual-art',
    title: 'Visual Art',
    titleKo: '비주얼 아트',
    description: '시각적 언어로 표현하는 예술적 실험',
    coverImage: 'https://ik.imagekit.io/t914/redux/visual-art/Collective_Vision.png',
    images: [
      'https://ik.imagekit.io/t914/redux/visual-art/Analog_Memories.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Collective_Vision.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Color_Theory.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Digital_Dreams.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Form_&_Void.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Metamorphosis.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Shadow_Play.png',
      'https://ik.imagekit.io/t914/redux/visual-art/Texture_Study.png',
    ],
  },
  'fashion-film': {
    id: 'fashion-film',
    title: 'Fashion Film',
    titleKo: '패션 필름',
    description: '움직임과 이야기가 있는 패션의 새로운 표현',
    coverImage: 'https://ik.imagekit.io/t914/redux/fashion-film/main-cover.jpg',
    videoUrl: 'https://ik.imagekit.io/t914/redux/fashion-film/main-video.mp4',
  },
  installation: {
    id: 'installation',
    title: 'Installation',
    titleKo: '인스톨레이션',
    description: '공간과 관객이 만나는 통합적 예술 경험',
    coverImage: 'https://ik.imagekit.io/t914/redux/process/공간__연출.png',
    processImages: [
      'https://ik.imagekit.io/t914/redux/process/공간__연출.png',
      'https://ik.imagekit.io/t914/redux/process/디렉팅.png',
      'https://ik.imagekit.io/t914/redux/process/디지털__웹_디자인.png',
      'https://ik.imagekit.io/t914/redux/process/아트_그래픽.png',
      'https://ik.imagekit.io/t914/redux/process/영상_&_편집.png',
      'https://ik.imagekit.io/t914/redux/process/홍보__브랜딩.png',
    ],
  },
  memory: {
    id: 'memory',
    title: 'Memory',
    titleKo: '메모리',
    description: '시간과 기억의 흔적을 담은 창작물',
    coverImage: 'https://ik.imagekit.io/t914/redux/memory/IMG_7237.jpg',
    images: [
      'https://ik.imagekit.io/t914/redux/memory/0C22A68E-AADF-4A8D-B5E7-44DDBA2EE64F.jpeg',
      'https://ik.imagekit.io/t914/redux/memory/83C1CE7D-97A9-400F-9403-60E89979528A.jpg',
      'https://ik.imagekit.io/t914/redux/memory/FullSizeRender(1).jpg',
      'https://ik.imagekit.io/t914/redux/memory/FullSizeRender.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_1728.jpeg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3452.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3454.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3455.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3481.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3491.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3492.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_3493.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_4339.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_4345.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_4348.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_4367.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_5380.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_5381.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_5382.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_5383.JPG',
      'https://ik.imagekit.io/t914/redux/memory/IMG_6418.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_6560.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7103.jpeg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7146.jpeg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7237.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7272.jpeg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7287.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7288.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7292.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7294.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7295.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7296.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7297.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7298.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7299.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7300.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7301.jpg',
      'https://ik.imagekit.io/t914/redux/memory/IMG_7302.jpg',
    ],
  },
} as const;

export const EXHIBITIONS: Exhibition[] = [
  {
    id: 'redux-showcase-2024',
    title: 'REDUX Showcase 2024',
    titleKo: 'REDUX 쇼케이스 2024',
    description: 'REDUX 디자이너들의 최신 작품을 선보이는 연례 쇼케이스',
    venue: 'Seoul Museum of Art',
    startDate: '2024-03-15',
    endDate: '2024-04-30',
    year: 2024,
    participants: ['Choi Eunsol', 'Park Parang', 'Lee Soyeon'],
    images: ['https://ik.imagekit.io/t914/redux/exhibitions/redux-showcase-2024-main.jpg'],
    status: 'upcoming',
    featured: true,
  },
  {
    id: 'seoul-fashion-week-2023',
    title: 'Seoul Fashion Week 2023',
    titleKo: '서울 패션위크 2023',
    description: 'REDUX 컬렉티브가 참여한 서울 패션위크 공식 프로그램',
    venue: 'DDP (Dongdaemun Design Plaza)',
    startDate: '2023-10-16',
    endDate: '2023-10-21',
    year: 2023,
    participants: ['Choi Eunsol', 'Jung Jiwoo'],
    images: ['https://ik.imagekit.io/t914/redux/exhibitions/seoul-fashion-week-2023-main.jpg'],
    status: 'past',
    featured: true,
  },
  {
    id: 'memory-traces-2023',
    title: 'Memory Traces',
    titleKo: '기억의 흔적',
    description: '시간과 기억을 주제로 한 멀티미디어 인스톨레이션 전시',
    venue: 'Alternative Space LOOP',
    startDate: '2023-07-01',
    endDate: '2023-08-15',
    year: 2023,
    participants: ['Park Parang', 'Lee Soyeon'],
    images: ['https://ik.imagekit.io/t914/redux/exhibitions/memory-traces-2023-main.jpg'],
    status: 'past',
    featured: false,
  },
  {
    id: 'fashion-film-festival-2023',
    title: 'International Fashion Film Festival',
    titleKo: '국제 패션 필름 페스티벌',
    description: 'REDUX의 패션 필름이 상영된 국제 페스티벌',
    venue: 'Megabox COEX',
    startDate: '2023-05-20',
    endDate: '2023-05-27',
    year: 2023,
    participants: ['Kim Gyeongsu', 'Jung Jiwoo'],
    images: ['https://ik.imagekit.io/t914/redux/exhibitions/fashion-film-festival-2023-main.jpg'],
    status: 'past',
    featured: false,
  },
  {
    id: 'redux-popup-2022',
    title: 'REDUX Pop-up Store',
    titleKo: 'REDUX 팝업 스토어',
    description: '한정판 작품과 협업 제품을 선보인 팝업 스토어',
    venue: 'Hyundai Department Store',
    startDate: '2022-12-01',
    endDate: '2022-12-31',
    year: 2022,
    participants: ['All REDUX Designers'],
    images: ['https://ik.imagekit.io/t914/redux/exhibitions/redux-popup-2022-main.jpg'],
    status: 'past',
    featured: false,
  },
];